version: "3"
services:
  reverseproxy:
    build:
      context: ../../udagram-reverse-proxy
    image: shasaang/udagram-reverse-proxy
  backend_user:
    build:
      context: ../../udagram-api-user
    image: shasaang/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed
    image: shasaang/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend
    image: shasaang/udagram-frontend
